# MultiPlot options saved by style manager
set ::MultiPlot::Plot0::title "::MultiPlot::Plot0"
set ::MultiPlot::Plot0::titlefont "Helvetica"
set ::MultiPlot::Plot0::titlefontsize "15"
set ::MultiPlot::Plot0::linewidth "2"
set ::MultiPlot::Plot0::linecolor "black"
set ::MultiPlot::Plot0::radius "1"
set ::MultiPlot::Plot0::fillcolor "Skyblue2"
set ::MultiPlot::Plot0::marker "none"
set ::MultiPlot::Plot0::ylabelfont "Helvetica"
set ::MultiPlot::Plot0::ylabelfontsize "10"
set ::MultiPlot::Plot0::xlabelfont "Helvetica"
set ::MultiPlot::Plot0::xlabelfontsize "10"
set ::MultiPlot::Plot0::ylabeltext "g(r)"
set ::MultiPlot::Plot0::xlabeltext "Distance (?)"
set ::MultiPlot::Plot0::ymin "         0"
set ::MultiPlot::Plot0::ymax "   84.2248"
set ::MultiPlot::Plot0::xmin "      0.05"
set ::MultiPlot::Plot0::xmax "     30.05"
set ::MultiPlot::Plot0::canh "400"
set ::MultiPlot::Plot0::canw "500"
::MultiPlot::Plot0::plothandle replot
